version: '3.4'

services:
  taskmanagementapi:
    build:
      context: ./TaskManagementAPI
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
     - "8081:8081"
    depends_on:
     - sqlserver
     - redis  
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
    networks:
     - productnetwork
    restart: on-failure

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: taskmanagement-sqlserver
    environment:
      MSSQL_SA_PASSWORD: "Password123456!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - productnetwork
  
  redis:
    image: redis:7-alpine
    container_name: taskmanagement-redis
    hostname: redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass TaskManagement2024
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - productnetwork

networks:
  productnetwork:

volumes:
  sqlvolume:
  redisdata:
