version: '3.8'
services:
  redis:
    image: redis
    container_name: taskmanagement-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data: